[[categories]]
id = "intro"
name = "Введение"

[[categories]]
id = "systems"
name = "Операционные системы"

[[categories]]
id = "package_managers"
name = "Управл. программным обеспечением"

[[categories]]
id = "prog"
name = "Программирование и разработка"

[[categories]]
id = "quick_fixes"
name = "Быстрое решение проблем"

[[docs.intro]]
id = "about"
name = "Что такое Linux?"

[[docs.intro]]
id = "free-software"
name = "Свободное программное обеспечение"

[[docs.intro]]
id = "helper"
name = "Пару слов про Helper"

[[docs.systems]]
id = "unix"
name = "Многообразие Unix-систем"

[[docs.systems]]
id = "linux"
name = "Зоопарк Linux-систем"

[[docs.systems]]
id = "adw-disadw"
name = "Достоинства и недостатки Linux"

[[docs.package_managers]]
id = "basics"
name = "Основы управления ПО в Linux"

[[docs.package_managers]]
id = "apt"
name = "APT (Debian, Ubuntu, Mint)"

[[docs.package_managers]]
id = "dpkg"
name = "dpkg (Debian, Ubuntu, Mint)"

[[docs.package_managers]]
id = "pacman"
name = "Pacman (Arch, Manjaro)"

[[docs.prog]]
id = "bash1"
name = "Программирование на Bash. Часть 1"

[[docs.prog]]
id = "bash2"
name = "Программирование на Bash. Часть 2"
